/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ficha01.view;

import ficha01.controller.UsuarioController;
import ficha01.model.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Mutisse
 */
public final class TelaPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaPerfil() {

        initComponents();
        setar_campos();
    }

    public void setar_campos() {
        for (Usuarios user : UsuarioController.lista()) {
            txtNome.setText(user.getNome());
            txtUser.setText(user.getUsuario());
            if (user.getGenero().equals("Masculino")) {
                rb_Masculino.setSelected(true);
            } else if (user.getGenero().equals("Feminino")) {
                rb_Femenino.setSelected(true);
            }
            pfSenha.setText(user.getSenha());
            pfSenha1.setText(user.getSenha());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnRegistar1 = new javax.swing.JButton();
        rb_Masculino = new javax.swing.JRadioButton();
        rb_Femenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCsenha = new javax.swing.JCheckBox();
        pfSenha = new javax.swing.JPasswordField();
        pfSenha1 = new javax.swing.JPasswordField();
        btnLimpar2 = new javax.swing.JButton();
        btnLimpar3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meu Perfil");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(170, 20, 260, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Genero:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 190, 70, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Login:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(270, 170, 140, 30);

        btnLimpar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar.setText("Cancelar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar);
        btnLimpar.setBounds(30, 370, 130, 28);

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.setEnabled(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel3.add(txtUser);
        txtUser.setBounds(260, 210, 160, 28);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Senha:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 290, 54, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Confirmar senha:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(170, 290, 135, 22);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNome.setEnabled(false);
        jPanel3.add(txtNome);
        txtNome.setBounds(30, 130, 390, 28);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/user.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(480, 110, 110, 130);

        btnRegistar1.setBackground(new java.awt.Color(204, 255, 255));
        btnRegistar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistar1.setText("Salvar");
        btnRegistar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistar1);
        btnRegistar1.setBounds(460, 370, 130, 28);

        buttonGroup1.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        rb_Masculino.setEnabled(false);
        jPanel3.add(rb_Masculino);
        rb_Masculino.setBounds(130, 180, 100, 20);

        rb_Femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Femenino.setText("Femenino");
        rb_Femenino.setEnabled(false);
        jPanel3.add(rb_Femenino);
        rb_Femenino.setBounds(130, 210, 100, 20);

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 170, 220, 80);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 100, 90, 22);

        jCsenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCsenha.setText("Mostrar a Senha ");
        jCsenha.setEnabled(false);
        jCsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCsenhaActionPerformed(evt);
            }
        });
        jPanel3.add(jCsenha);
        jCsenha.setBounds(30, 260, 160, 21);

        pfSenha.setText("jPasswordField1");
        pfSenha.setEnabled(false);
        jPanel3.add(pfSenha);
        pfSenha.setBounds(170, 320, 110, 30);

        pfSenha1.setText("jPasswordField1");
        pfSenha1.setEnabled(false);
        jPanel3.add(pfSenha1);
        pfSenha1.setBounds(30, 320, 110, 30);

        btnLimpar2.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar2.setText("Limpar");
        btnLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar2);
        btnLimpar2.setBounds(180, 370, 130, 28);

        btnLimpar3.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar3.setText("Atualizar");
        btnLimpar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar3);
        btnLimpar3.setBounds(320, 370, 130, 28);

        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 600, 400);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 620, 420);

        setBounds(0, 0, 639, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed


    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnRegistar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistar1ActionPerformed
        Usuarios add = new Usuarios();
        add.setNome(txtNome.getText());
        add.setUsuario(txtUser.getText());
        if (rb_Masculino.isSelected()) {
            add.setGenero(rb_Masculino.getActionCommand());
        } else if (rb_Femenino.isSelected()) {
            add.setGenero(rb_Femenino.getActionCommand());
        }
        add.setSenha(pfSenha.getText());

        try {
            if (txtNome.getText().length() > 1) {
                if (txtUser.getText().length() > 1) {
                    if (pfSenha.getText().length() > 3 || pfSenha1.getText().length() > 3) {
                        if (pfSenha.getText().equals(pfSenha1.getText())) {
                            UsuarioController.create(add);
                            JOptionPane.showMessageDialog(null, "Registado com sucesso!", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "Senha inválida.\n a primeira senha nao e igual a Segunda !", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Senha inválida.\nCombine pelo menos 4 caracteres!", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {

                }
            } else {

            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro de formatação. Verifique os seus dados!", "", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistar1ActionPerformed

    private void jCsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCsenhaActionPerformed
        if (jCsenha.isSelected()) {
            pfSenha1.setEchoChar((char) 0);
            pfSenha.setEchoChar((char) 0);
        } else {
            pfSenha.setEchoChar('*');
            pfSenha1.setEchoChar('*');

        }
    }//GEN-LAST:event_jCsenhaActionPerformed
    public void LimparCampos() {
        txtNome.setText("");
        txtUser.setText("");
        pfSenha.setText("");
        pfSenha1.setText("");
        buttonGroup1.clearSelection();
    }
    private void btnLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar2ActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimpar2ActionPerformed

    private void btnLimpar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar3ActionPerformed
        txtNome.setEnabled(true);
        jCsenha.setEnabled(true);
        txtUser.setEnabled(true);
        pfSenha.setEnabled(true);
        pfSenha1.setEnabled(true);
        rb_Femenino.setEnabled(true);
        rb_Masculino.setEnabled(true);
    }//GEN-LAST:event_btnLimpar3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnLimpar3;
    private javax.swing.JButton btnRegistar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPasswordField pfSenha1;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
