/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ficha01.view;

import ficha01.controller.UsuarioController;
import ficha01.model.Usuarios;

import javax.swing.JOptionPane;

/**
 *
 * @author Mutisse
 */
public class TelaRegistoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistoUsuario
     */
    public TelaRegistoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pfSenha2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        txtApelido = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnRegistar1 = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        rb_Masculino = new javax.swing.JRadioButton();
        rb_Femenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCsenha = new javax.swing.JCheckBox();
        pfSenha = new javax.swing.JPasswordField();
        pfSenha1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pfSenha2.setBackground(new java.awt.Color(204, 204, 204));
        pfSenha2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Usuários");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pfSenha2.add(jLabel1);
        jLabel1.setBounds(100, 30, 246, 29);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Genero:");
        pfSenha2.add(jLabel2);
        jLabel2.setBounds(40, 200, 70, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Login:");
        pfSenha2.add(jLabel3);
        jLabel3.setBounds(290, 180, 140, 30);

        btnLimpar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar.setText("Cancelar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        pfSenha2.add(btnLimpar);
        btnLimpar.setBounds(80, 400, 130, 31);

        txtApelido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApelidoActionPerformed(evt);
            }
        });
        pfSenha2.add(txtApelido);
        txtApelido.setBounds(290, 140, 220, 28);

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        pfSenha2.add(txtUser);
        txtUser.setBounds(290, 210, 210, 28);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Senha:");
        pfSenha2.add(jLabel5);
        jLabel5.setBounds(30, 300, 54, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Confirmar senha:");
        pfSenha2.add(jLabel6);
        jLabel6.setBounds(170, 300, 135, 22);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Apelido:");
        pfSenha2.add(jLabel7);
        jLabel7.setBounds(290, 110, 90, 20);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfSenha2.add(txtNome);
        txtNome.setBounds(30, 140, 220, 28);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/user.png"))); // NOI18N
        pfSenha2.add(jLabel8);
        jLabel8.setBounds(410, 20, 100, 100);

        btnRegistar1.setBackground(new java.awt.Color(204, 255, 255));
        btnRegistar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistar1.setText("Registar");
        btnRegistar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistar1ActionPerformed(evt);
            }
        });
        pfSenha2.add(btnRegistar1);
        btnRegistar1.setBounds(360, 400, 130, 31);

        btnLimpar1.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        pfSenha2.add(btnLimpar1);
        btnLimpar1.setBounds(220, 400, 130, 31);

        buttonGroup1.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        pfSenha2.add(rb_Masculino);
        rb_Masculino.setBounds(130, 190, 100, 25);

        buttonGroup1.add(rb_Femenino);
        rb_Femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Femenino.setText("Femenino");
        pfSenha2.add(rb_Femenino);
        rb_Femenino.setBounds(130, 220, 100, 25);

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pfSenha2.add(jLabel9);
        jLabel9.setBounds(30, 180, 220, 80);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");
        pfSenha2.add(jLabel4);
        jLabel4.setBounds(30, 120, 90, 22);

        jCsenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCsenha.setText("Mostrar a Senha ");
        jCsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCsenhaActionPerformed(evt);
            }
        });
        pfSenha2.add(jCsenha);
        jCsenha.setBounds(30, 270, 160, 25);

        pfSenha.setText("jPasswordField1");
        pfSenha2.add(pfSenha);
        pfSenha.setBounds(170, 330, 110, 30);

        pfSenha1.setText("jPasswordField1");
        pfSenha2.add(pfSenha1);
        pfSenha1.setBounds(30, 330, 110, 30);

        getContentPane().add(pfSenha2);
        pfSenha2.setBounds(0, 0, 530, 460);

        setSize(new java.awt.Dimension(549, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        LimparCampos();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApelidoActionPerformed

    private void btnRegistar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistar1ActionPerformed
        Usuarios add = new Usuarios();
        add.setNome(txtNome.getText() + " " + txtApelido.getText());
        add.setUsuario(txtUser.getText());
        if (rb_Masculino.isSelected()) {
            add.setGenero(rb_Masculino.getActionCommand());
        } else if (rb_Femenino.isSelected()) {
            add.setGenero(rb_Femenino.getActionCommand());
        }
        add.setSenha(pfSenha.getText());
       

        try {
            if (txtNome.getText().length() > 1) {
                if (txtApelido.getText().length() > 1) {
                    if (pfSenha.getText().length() > 3 || pfSenha1.getText().length() > 3) {
                        if (pfSenha.getText().equals(pfSenha1.getText())) {
                            UsuarioController.create(add);
                            JOptionPane.showMessageDialog(null, "Registado com sucesso!", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                            new TelaLogin().setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Senha inválida.\n a primeira senha nao e igual a Segunda !", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Senha inválida.\nCombine pelo menos 4 caracteres!", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {

                }
            } else {

            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro de formatação. Verifique os seus dados!", "", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistar1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jCsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCsenhaActionPerformed
        if (jCsenha.isSelected()) {
            pfSenha1.setEchoChar((char) 0);
            pfSenha.setEchoChar((char) 0);
        } else {
            pfSenha.setEchoChar('*');
            pfSenha1.setEchoChar('*');

        }
    }//GEN-LAST:event_jCsenhaActionPerformed
    public void LimparCampos() {
        txtNome.setText("");
        txtApelido.setText("");
        txtUser.setText("");
        pfSenha.setText("");
        pfSenha1.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnRegistar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPasswordField pfSenha1;
    private javax.swing.JPanel pfSenha2;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
