/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ficha01.view;

import ficha01.controller.ClienteController;
import ficha01.model.Cliente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mutisse
 */
public final class TelaRegistar extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaRegistar() {
        linhas = new Object[][]{};
        sdf = new SimpleDateFormat("dd/MMMM/yyyy");
        initComponents();
        preencherTabela();
        setarId();
        FormatDatachoos();

    }

    public void FormatDatachoos() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MMMM/yyyy");
        String data = sdf.format(Calendar.getInstance().getTime());
        try {
            jDateChooser.setDate(sdf.parse(data));
            jDateChooser.setMaxSelectableDate(sdf.parse(data));

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conversão da data!");
        }
    }

    private void calcularValor() {
        float valor2, valorDivida = Float.parseFloat(spnValorDivida.getValue().toString());

        if (valorDivida <= 100.00) {
            valor2 = (float) (valorDivida + valorDivida * 0.4);
            lblValorApagar.setText(" " + Float.toString(valor2));
        } else if (valorDivida <= 500.00) {
            valor2 = (float) (valorDivida + valorDivida * 0.3);
            lblValorApagar.setText(" " + Float.toString(valor2));
        } else if (valorDivida <= 1000.00) {
            valor2 = (float) (valorDivida + valorDivida * 0.2);
            lblValorApagar.setText(" " + Float.toString(valor2));
        } else {
            valor2 = (float) (valorDivida + valorDivida * 0.15);
            lblValorApagar.setText(" " + Float.toString(valor2));
        }
    }

    private void setarId() {
        ClienteController controller = new ClienteController();
        controller.CaminhoPrincipal();

        Calendar now = Calendar.getInstance();

        String id = "";
        boolean existe = false;
        if (!ClienteController.lista().isEmpty()) {

            while (true) {

                id = ((int) (10000 * Math.random())) + " ";
                for (Cliente divida : ClienteController.lista()) {
                    if (id == null ? divida.getId() == null : id.equals(divida.getId())) {
                        existe = true;

                        break;
                    }
                }
                if (existe == false) {
                    break;
                }
            }
        } else {
            id = ((int) (10000 * Math.random())) + " ";
        }

        lbl_id.setText(" " + id);
    }

    private void preencherTabela() {

        Cliente[] array = new Cliente[ClienteController.lista().size()];
        int i = 0;
        for (Cliente d : ClienteController.lista()) {
            array[i] = d;
            i++;
        }

        Arrays.sort(array);   //FAZ A ORDENAÇÃO DO ARRAY "DÍVIDAS" EM ORDEM CRESCENTE DOS VALORES A PAGAR
        model.setNumRows(0);
        for (Cliente dadosCliente : array) {
            dataf = sdf.format(dadosCliente.getData());
            model.addRow(new Object[]{dadosCliente.getId(), dadosCliente.getNomeDevedor() + " " + dadosCliente.getApelidoDevedor(), dadosCliente.getGenero(), dadosCliente.getContacto(), dataf,
                dadosCliente.getValorDivida(), dadosCliente.getValorAPagar(), dadosCliente.getRemanescente(), dadosCliente.getEstadoDivida()});

        }
    }

    public void LimpatCampos() {
        txtNome.setText(null);
        txtApelido.setText(null);
        lblValorApagar.setText(null);
        lbl_id.setText(null);
        txf_contacto.setText(null);
        buttonGroup.clearSelection();
        spnValorDivida.setValue(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_regitrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtApelido = new javax.swing.JTextField();
        spnValorDivida = new javax.swing.JSpinner();
        lblValorApagar = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txf_contacto = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        rb_Masculino = new javax.swing.JRadioButton();
        rb_Femenino = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/FundoRegistarDividas.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 10, 120, 100);

        btn_regitrar.setBackground(new java.awt.Color(204, 255, 255));
        btn_regitrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_regitrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/salary2.png"))); // NOI18N
        btn_regitrar.setText("Registar Divida");
        btn_regitrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regitrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_regitrar);
        btn_regitrar.setBounds(430, 350, 160, 30);

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/clean.png"))); // NOI18N
        jButton2.setText("Limpar");
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 350, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Id:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 90, 30, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 130, 80, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Contacto:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 130, 90, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Data:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 200, 70, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Valor a Pagar:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(460, 200, 130, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Valor da  Divida:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 200, 140, 22);

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtNome);
        txtNome.setBounds(10, 160, 150, 27);

        txtApelido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtApelido);
        txtApelido.setBounds(210, 160, 160, 27);

        spnValorDivida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spnValorDivida.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 5000.0d, 50.0d));
        spnValorDivida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnValorDividaStateChanged(evt);
            }
        });
        spnValorDivida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                spnValorDividaMouseReleased(evt);
            }
        });
        spnValorDivida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnValorDividaKeyReleased(evt);
            }
        });
        jPanel1.add(spnValorDivida);
        spnValorDivida.setBounds(310, 230, 110, 30);

        lblValorApagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorApagar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblValorApagar);
        lblValorApagar.setBounds(470, 230, 120, 30);

        lbl_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 51, 51));
        lbl_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_id);
        lbl_id.setBounds(80, 90, 80, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" Registro de Dívida");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(110, 20, 360, 50);

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/Cancel.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 350, 130, 30);

        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 220, 120, 70);

        try {
            txf_contacto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+258)  ## ### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txf_contacto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txf_contacto);
        txf_contacto.setBounds(420, 160, 170, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Apelido:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 130, 70, 22);

        buttonGroup.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        jPanel1.add(rb_Masculino);
        rb_Masculino.setBounds(20, 230, 100, 20);

        buttonGroup.add(rb_Femenino);
        rb_Femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Femenino.setText("Femenino");
        jPanel1.add(rb_Femenino);
        rb_Femenino.setBounds(20, 260, 100, 20);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Genero:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 190, 70, 20);

        jDateChooser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jDateChooser);
        jDateChooser.setBounds(140, 230, 140, 30);

        jTabbedPane.addTab(" Registar Dívidas", jPanel1);

        jPanel2.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/FundoRegistarDividas.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(500, 30, 100, 90);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditTable(int rowIndex, int colIndex) {
                return false;
            }
        };
        String[] colunas = new String[]{"ID", "Nome","Genero","Contacto", "Data", "Emprestado", "A Pagar", "Remanescente", "Estado"};
        model = new DefaultTableModel(linhas, colunas);
        jTable1.setModel(model);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(45);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(115);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(83);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(60);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 580, 230);

        jTabbedPane.addTab("Dados Dos Devedores", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regitrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regitrarActionPerformed
        try {
            Cliente add = new Cliente();
            if (txtNome.getText().length() > 1) {
                if (txtApelido.getText().length() > 1) {
                    if ((Float.parseFloat(spnValorDivida.getValue().toString()) != 0)
                            && (Float.parseFloat(spnValorDivida.getValue().toString()) <= 5000)
                            && (Float.parseFloat(lblValorApagar.getText()) != 0)) {

                        add.setId(lbl_id.getText());
                        add.setNomeDevedor(txtNome.getText());
                        add.setApelidoDevedor(txtApelido.getText());
                        add.setContacto(txf_contacto.getText());
                        add.setData(jDateChooser.getDate());
                        if (rb_Masculino.isSelected()) {
                            add.setGenero(rb_Masculino.getActionCommand());
                        } else if (rb_Femenino.isSelected()) {
                            add.setGenero(rb_Femenino.getActionCommand());
                        }
                        add.setValorDivida(Float.parseFloat(spnValorDivida.getValue().toString()));
                        add.setValorAPagar(Float.parseFloat(lblValorApagar.getText()));
                        add.setRemanescente(add.getValorAPagar());
                        add.setEstadoDivida(false);

                        ClienteController.create(add);
                        JOptionPane.showMessageDialog(rootPane, "Registado com sucesso!");
                        LimpatCampos();
                        setarId();
                        preencherTabela();
                        jTabbedPane.setSelectedIndex(1);

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Valor de empréstimo inválido!");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Apelido inválido!");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nome inválido!");
            }

        } catch (NumberFormatException ex) {

        } catch (NullPointerException ex) {

        }
    }//GEN-LAST:event_btn_regitrarActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!txtNome.getText().isEmpty() || !txtApelido.getText().isEmpty()) {
            if (0 == JOptionPane.showConfirmDialog(rootPane, "Deseja cancelar este registo?\nOs dados introduzidos serão perdidos.", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)) {

            }
        } else {
            try {

            } catch (Exception e) {
                JOptionPane.showInternalMessageDialog(null, " Erro! nao selecionar a tela que ja esta em execucao", "notificacao", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void spnValorDividaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnValorDividaKeyReleased
        calcularValor();
    }//GEN-LAST:event_spnValorDividaKeyReleased

    private void spnValorDividaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnValorDividaMouseReleased
        calcularValor();
    }//GEN-LAST:event_spnValorDividaMouseReleased

    private void spnValorDividaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnValorDividaStateChanged
        calcularValor();
    }//GEN-LAST:event_spnValorDividaStateChanged
// cridas 
    private DefaultTableModel model;
    private final Object[][] linhas;
    private String dataf;
    private SimpleDateFormat sdf;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regitrar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblValorApagar;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JSpinner spnValorDivida;
    private javax.swing.JFormattedTextField txf_contacto;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
