/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ficha01.view;

import ficha01.controller.ClienteController;
import ficha01.controller.UsuarioController;
import ficha01.model.Usuarios;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Mutisse
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public TelaLogin() {
        initComponents();
        ClienteController controller = new ClienteController();
        controller.CaminhoPrincipal();
        URL url = this.getClass().getResource("/ficha01/view/icons/icon-lock.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    public void Login() {
        TelaMenu tMenu = new TelaMenu();
        if (!txtUsuario.getText().isEmpty()) {
            if (!pfSenha.getText().isEmpty()) {
                boolean found = false;
                if (tentativaAtual <= maximoTentativas && found == false) {
                    String usuario = txtUsuario.getText();
                    String senha = pfSenha.getText();

                    for (Usuarios user : UsuarioController.lista()) {
                        if (usuario.equals(user.getUsuario()) && senha.equals(user.getSenha())) {
                            found = true;
                            this.dispose();
                            JOptionPane.showMessageDialog(null, "Bem vindo Senhor!  " + user.getNome());
                            tentativaAtual = maximoTentativas + 1;
                            new TelaMenu().setVisible(true);

                            break;
                        }
                    }
                    if (found == false) {
                        maximoTentativas -= 1;
                        JOptionPane.showMessageDialog(rootPane, "Combinação de usuário e senha incorrecta ! Voce ficou com " + maximoTentativas + " Tentativas", " ", JOptionPane.ERROR_MESSAGE);
                        txtUsuario.setText("");
                        pfSenha.setText("");
                        tentativaAtual = tentativaAtual + 1;

                    }
                } else if (tentativaAtual == 1) {
                    txtUsuario.setEnabled(false);
                    pfSenha.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Você ultrapassou o número de tentativas, Usuario Bloqueado", "", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Introduza a sua senha!", "", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Introduza o seu ID!", "", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btAutenticar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        btn_ocultar = new javax.swing.JButton();
        btn_desecultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Autenticação");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 350, 50);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 200, 120, 22);

        btAutenticar.setBackground(new java.awt.Color(204, 255, 255));
        btAutenticar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAutenticar.setText("Entrar");
        btAutenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutenticarActionPerformed(evt);
            }
        });
        jPanel1.add(btAutenticar);
        btAutenticar.setBounds(380, 350, 110, 28);

        txtUsuario.setBackground(new java.awt.Color(242, 242, 242));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 255, 255)));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(340, 230, 190, 25);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Senha:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 270, 70, 22);

        pfSenha.setBackground(new java.awt.Color(242, 242, 242));
        pfSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 255, 255)));
        pfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(pfSenha);
        pfSenha.setBounds(340, 300, 190, 24);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/Cancel.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 10, 17, 17);

        btn_ocultar.setBackground(new java.awt.Color(214, 217, 223));
        btn_ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/ocultar.png"))); // NOI18N
        btn_ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocultarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ocultar);
        btn_ocultar.setBounds(540, 300, 32, 25);

        btn_desecultar.setBackground(new java.awt.Color(214, 217, 223));
        btn_desecultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/visualizar.png"))); // NOI18N
        btn_desecultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desecultarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_desecultar);
        btn_desecultar.setBounds(540, 300, 32, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha01/view/icons/HOME-LOAN-HIKE1200X800-620x413.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(610, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAutenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutenticarActionPerformed
        Login();
    }//GEN-LAST:event_btAutenticarActionPerformed

    private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_ocultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocultarActionPerformed
        btn_ocultar.setVisible(false);
        btn_desecultar.setVisible(true);
        pfSenha.setEchoChar((char) 0);
    }//GEN-LAST:event_btn_ocultarActionPerformed

    private void btn_desecultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desecultarActionPerformed
        pfSenha.setEchoChar('•');
        btn_ocultar.setVisible(true);
        btn_desecultar.setVisible(false);
    }//GEN-LAST:event_btn_desecultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
    int tentativaAtual = 1;
    int maximoTentativas = 3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAutenticar;
    private javax.swing.JButton btn_desecultar;
    private javax.swing.JButton btn_ocultar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
