/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.UsuarioDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import model.RelatorioPdf;
import model.Usuario;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Klesia
 */
public final class relatorio extends javax.swing.JInternalFrame {

    Usuario add = new Usuario();

    /**
     * Creates new form relatorio
     */
    public relatorio() {
        initComponents();
        showPieChart(new UsuarioDao().ListarTodos());
     //   somatorio(new UsuarioDao().ListarTodos());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void somatorio(List<Usuario> usuarios) {
        usuarios.stream().map((user) -> {
            if (user.getGenero().equalsIgnoreCase("Masculino")) {
                msaculino++;
            } else if (user.getGenero().equalsIgnoreCase("Feminino")) {
                femenino++;
            }
            return user;
        }).forEachOrdered((_item) -> {
            totalRegistrados = msaculino + femenino;
        });

        System.out.println(totalRegistrados + " " + msaculino + " " + femenino);
    }

    /*=============================================================================*/
    public void showPieChart(List<Usuario> usuarios) {
        usuarios.stream().map((user) -> {
            if (user.getGenero().equalsIgnoreCase("Masculino")) {
                msaculino++;
            } else if (user.getGenero().equalsIgnoreCase("Feminino")) {
                femenino++;
            }
            return user;
        }).forEachOrdered((_item) -> {
            totalRegistrados = msaculino + femenino;
        });
        //
        DefaultPieDataset barDataset = new DefaultPieDataset();
        barDataset.setValue("Feminino", (int) femenino);
        barDataset.setValue("Masculino ", (int) msaculino);
        barDataset.setValue("Total de Usuario", (int) totalRegistrados);

        //create chart
        JFreeChart piechart = ChartFactory.createPieChart3D(" Representação em género ", barDataset, true, true, false);//explain

        PiePlot piePlot = (PiePlot) piechart.getPlot();

        //changing pie chart blocks colors
        piePlot.setSectionPaint((int) femenino, new Color(255, 255, 102));
        piePlot.setSectionPaint((int) msaculino, new Color(102, 255, 102));
        piePlot.setSectionPaint((int) totalRegistrados, Color.GREEN);
        piePlot.setBackgroundPaint(Color.white);

        //create chartPanel to display chart(graph)
        ChartPanel pieChartPanel = new ChartPanel(piechart);
        pieChartPanel.setBounds(5, 5, 365, 245);
        showPieChart.add(pieChartPanel, BorderLayout.CENTER);
        showPieChart.validate();

        jLabel3.setText(String.valueOf("Masculino: " + msaculino));
        jLabel1.setText(String.valueOf("Femenino: " + femenino));
        jLabel2.setText(String.valueOf("Toltal: " + totalRegistrados));
    }

    @SuppressWarnings("unchecked")

    public void GerarRelatorio() {
        new RelatorioPdf().gerarRelatorio(jLabel2.getText(), jLabel1.getText(), jLabel3.getText());
        JOptionPane.showMessageDialog(rootPane, "Relatório gerado com sucesso \nna pasta do projecto!");

    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showPieChart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setLayout(null);

        showPieChart.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout showPieChartLayout = new javax.swing.GroupLayout(showPieChart);
        showPieChart.setLayout(showPieChartLayout);
        showPieChartLayout.setHorizontalGroup(
            showPieChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        showPieChartLayout.setVerticalGroup(
            showPieChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        jPanel1.add(showPieChart);
        showPieChart.setBounds(10, 60, 375, 255);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(410, 160, 150, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 210, 150, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 120, 150, 20);

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 290, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        setBounds(0, 0, 610, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.GerarRelatorio();
    }//GEN-LAST:event_jButton1ActionPerformed

    int msaculino, femenino, totalRegistrados;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel showPieChart;
    // End of variables declaration//GEN-END:variables
}
