/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.Conector;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Klesia
 */
public class TelaLogin extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null; //pst quer dizer  PreparedStatement
    ResultSet rst = null;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        conexao = Conector.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void limparCampos() {

        txt_Username.setText(null);
        tp_senha.setText(null);

    }

    void logar() {
        String SQL = "SELECT * FROM tbUsuarios where Username = ? and Senha=?";
        try {

            pst = conexao.prepareStatement(SQL);
            pst.setString(1, txt_Username.getText());
            pst.setString(2, tp_senha.getText());
            rst = pst.executeQuery();

            if (rst.next()) {
                TelaMenu tMenu = new TelaMenu();
                if (rst.getString(7).equalsIgnoreCase("Activo")) {
                    tMenu.lbl_Usuario.setText(rst.getString(2));
                    tMenu.setVisible(true);
                    this.dispose();
                    //
//                    tMenu.lbl_Perfil.setText(rst.getString(7));
//                    tMenu.lbl_Perfil.setForeground(Color.red);
                    //   tMenu.lbl_addp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examedefp2022/view/icons/admin.png")));

//                    tMenu.lbl_Usuario.setForeground(Color.red);
                } else if (rst.getString(8).equalsIgnoreCase("Inativo")) {
                    JOptionPane.showInternalMessageDialog(null, "Usuário bloqueado acesso não permetido!", "Notificação", JOptionPane.INFORMATION_MESSAGE);
                    limparCampos();
                } else if (rst.getString(8).equalsIgnoreCase("removido")) {
                    JOptionPane.showInternalMessageDialog(null, "Esse Usuario não existe!", "Notificação", JOptionPane.INFORMATION_MESSAGE);
                    limparCampos();
                } // fim status
            } else if (tentativaAtual <= maximoTentativas) {
                JOptionPane.showMessageDialog(null, "Combinação de credencias incorrecta.\n tentativas restantes" + maximoTentativas, "Notificação", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                maximoTentativas -= 1;
                tentativaAtual = tentativaAtual + 1;
            } else if (tentativaAtual > maximoTentativas) {
                btn_ocultar.setVisible(false);
                btn_desecultar.setVisible(false);
                tp_senha.setEnabled(false);
                txt_Username.setEnabled(false);

                JOptionPane.showMessageDialog(null, " Tentativas Esgotadas!!\n Usuario Bloqueado", "Notificação", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro de conexao com a base d e dados!!", "Notificação", JOptionPane.ERROR_MESSAGE);

        }

    }

    void camposVazios() {
        if (!txt_Username.getText().isEmpty()) {
            if (!tp_senha.getText().isEmpty()) {
                logar();
            } else {
                JOptionPane.showMessageDialog(null, "Introduza a sua senha!", "", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Introduza o seu e-mail", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tp_senha = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        btn_desecultar = new javax.swing.JButton();
        btn_ocultar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        txt_Username.setBackground(new java.awt.Color(204, 204, 204));
        txt_Username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_UsernameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Username);
        txt_Username.setBounds(80, 120, 223, 25);

        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 90, 70, 20);

        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 154, 70, 20);

        tp_senha.setBackground(new java.awt.Color(204, 204, 204));
        tp_senha.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        tp_senha.setText("jPasswordField1");
        tp_senha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        tp_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tp_senhaKeyPressed(evt);
            }
        });
        jPanel1.add(tp_senha);
        tp_senha.setBounds(80, 180, 220, 25);

        btn_entrar.setBackground(new java.awt.Color(204, 255, 255));
        btn_entrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(51, 51, 51));
        btn_entrar.setText("iniciar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        btn_entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_entrarKeyPressed(evt);
            }
        });
        jPanel1.add(btn_entrar);
        btn_entrar.setBounds(140, 240, 120, 29);

        btn_desecultar.setBackground(new java.awt.Color(214, 217, 223));
        btn_desecultar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btn_desecultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desecultarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_desecultar);
        btn_desecultar.setBounds(300, 180, 32, 25);

        btn_ocultar.setBackground(new java.awt.Color(214, 217, 223));
        btn_ocultar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btn_ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocultarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ocultar);
        btn_ocultar.setBounds(300, 180, 32, 25);

        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setMnemonic('X');
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(360, 5, 30, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 30);

        jLabel4.setText("registar-se");
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 210, 60, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        camposVazios();
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_entrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_entrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dispose();
            camposVazios();
        }
    }//GEN-LAST:event_btn_entrarKeyPressed

    private void tp_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tp_senhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_entrar.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt_Username.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btn_entrar.requestFocus();
        }
    }//GEN-LAST:event_tp_senhaKeyPressed

    private void txt_UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tp_senha.requestFocus();
        }

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tp_senha.requestFocus();
        }

    }//GEN-LAST:event_txt_UsernameKeyPressed

    private void btn_desecultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desecultarActionPerformed
        tp_senha.setEchoChar('•');
        btn_ocultar.setVisible(true);
        btn_desecultar.setVisible(false);
    }//GEN-LAST:event_btn_desecultarActionPerformed

    private void btn_ocultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocultarActionPerformed
        btn_ocultar.setVisible(false);
        btn_desecultar.setVisible(true);
        tp_senha.setEchoChar((char) 0);
    }//GEN-LAST:event_btn_ocultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel4AncestorAdded

    }//GEN-LAST:event_jLabel4AncestorAdded

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
        new TelaUsario().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    int tentativaAtual = 1;
    int maximoTentativas = 3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_desecultar;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_ocultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField tp_senha;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
