/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.Conector;
import dao.UsuarioDao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Base64;
import java.util.List;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableModel;
import model.Usuario;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Klesia
 */
public final class TelaUser extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null; //pst quer dizer  PreparedStatement
    ResultSet rst = null;

    /**
     * Creates new form NewJInternalFrame
     */
    public TelaUser() {
        initComponents();

        btn_atualizar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_atualizar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        jTxt_biografia.setVisible(false);
        prencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Setar campos    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   esse metodo vai prencher os campos  de formulario funcionario com falaores perenchidos na tabela 
     */
    public void Find() {
        conexao = Conector.conectar();
        String sql = " select Id_User as ID ,Nome as Nome, Genero as Gênero,email as e_mail, Username as Username,  estado as Estado,  Senha as Senha,  biografia as biografia from tbUsuarios where Nome like ?";
        try {

            pst = conexao.prepareStatement(sql);
            pst.setString(1, txt_pesquisar.getText() + "%");
            rst = pst.executeQuery();
            jT_Usuario.setModel(DbUtils.resultSetToTableModel(rst));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "  Registro nao Encontrado", "Notificação", WARNING_MESSAGE);

        } finally {
            try {
                conexao.close();
                pst.close();
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e + " Erro na conexao");
            }
        }

    }

    public void setCampos() {

        try {
            int setar = jT_Usuario.getSelectedRow();
            lbl_Codigo.setText(jT_Usuario.getModel().getValueAt(setar, 0).toString());
            txt_Nome.setText(jT_Usuario.getModel().getValueAt(setar, 1).toString());
            if (jT_Usuario.getModel().getValueAt(setar, 2).equals("Masculino")) {
                rb_Masculino.setSelected(true);
            } else if (jT_Usuario.getModel().getValueAt(setar, 2).equals("Feminino")) {
                rb_Femenino.setSelected(true);
            }

            txt_email.setText(jT_Usuario.getModel().getValueAt(setar, 3).toString());
            txt_username.setText(jT_Usuario.getModel().getValueAt(setar, 4).toString());

            if (jT_Usuario.getModel().getValueAt(setar, 5).equals("Activo")) {
                ch_permitido.setSelected(true);
            } else if (jT_Usuario.getModel().getValueAt(setar, 5).equals("Inativo")) {
                ch_naoPermitido.setSelected(true);
            }

            String str = this.descriptografia(jT_Usuario.getModel().getValueAt(setar, 6).toString());
            pf_Senha.setText(str);
            pf_SenhaConfimar.setText(str);

            jTxt_biografia.setText(jT_Usuario.getModel().getValueAt(setar, 7).toString());

            //
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e + " Erro!! Campo Selecionado esta vazio", "Notificação", JOptionPane.ERROR);
        }

    }

    void veriaficarUsuario() {
        int contt = 0;
        for (int i = 0; i < jT_Usuario.getRowCount(); i++) {
            if (txt_Nome.getText().equals(jT_Usuario.getModel().getValueAt(i, 1)) && txt_username.getText().equals(jT_Usuario.getModel().getValueAt(i, 3)) && txt_email.getText().equals(jT_Usuario.getModel().getValueAt(i, 4))) {
                contt = 1;
            }
        }

        if (contt >= 1) {
            int i = 0;
            i = JOptionPane.showConfirmDialog(null, "Este Usuário já existe", "Notificação ", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                System.out.println(" Preencher os dados ");
            }
        } else {

        }

    }

    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ criptografia ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     faz a criptografia da senha 
     */
    String criptografia(String str) {
        return new String(Base64.getEncoder().encode(str.getBytes()));
    }

    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ validar email ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     defaz a criptografia da senh.
     */
    String descriptografia(String str) {
        return new String(Base64.getDecoder().decode(str.getBytes()));
    }

    /* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ prenche a tabela    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   
     */
    void prencherTabela() {
        try {
            UsuarioDao CDao = new UsuarioDao();
            List<Usuario> Lista = CDao.ListarTodos();
            DefaultTableModel newModelTable = (DefaultTableModel) jT_Usuario.getModel();
            newModelTable.setRowCount(0);

            Lista.forEach((Usuario user) -> {

                newModelTable.addRow(new Object[]{user.getId(), user.getNome(),
                    user.getGenero(), user.getEmail(), user.getNomeUsuario(),
                    user.getEstado(), this.criptografia(user.getSenha()), user.getBiografia()});
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + " Erro ao preencher atabela ", "Notificação", JOptionPane.ERROR);
        }
    }

    boolean validarEmail(String email) {
        String emailRegular = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
        Pattern emailPatt = Pattern.compile(emailRegular, Pattern.CASE_INSENSITIVE);
        Matcher matcher = emailPatt.matcher(email);
        return matcher.find();

    }

    void setarCodigo() {
        UsuarioDao Dao = new UsuarioDao();
        lbl_Codigo.setText("" + Dao.GerarCodigo());
        // parte da senha 
        Random random = new Random(); // onde e gerado os cod. de funcionario
        int codgo = random.nextInt(9000);
        while (codgo < 1000) {
            codgo = random.nextInt(9000);

        }// fim while
        pf_Senha.setText("@" + codgo);
        pf_SenhaConfimar.setText("@" + codgo);
    }

    void validar() {
        if (pf_Senha.getText().length() > 3 || pf_SenhaConfimar.getText().length() > 3) {
            if (pf_Senha.getText().equals(pf_SenhaConfimar.getText())) {

            } else {
                JOptionPane.showMessageDialog(null, "Senha invalida.\n As Senhas são diferentes!", "Notificacao", JOptionPane.WARNING_MESSAGE);
                pf_Senha.setForeground(Color.RED);
                pf_SenhaConfimar.setForeground(Color.RED);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senha inválida.\nCombine pelo menos 4 caracteres!", "Notificacao", JOptionPane.INFORMATION_MESSAGE);
            pf_Senha.setForeground(Color.RED);
            pf_SenhaConfimar.setForeground(Color.RED);
        }

    }

    void vaidarEmail() {
        if (this.validarEmail(txt_email.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Email Digitado Inválido! Por Favor Introduza um email válido", "Atenção", JOptionPane.WARNING_MESSAGE);
            txt_email.setForeground(Color.RED);
        } else {

        }
    }

    public void limparCampos() {
        txt_Nome.setText(null);
        txt_pesquisar.setText(null);
        txt_email.setText(null);
        jTxt_biografia.setText(null);
        pf_Senha.setText(null);
        pf_SenhaConfimar.setText(null);
        lbl_Codigo.setText(null);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        prencherTabela();

    }

    void atualizar() {

        try {
            Usuario add = new Usuario();
            add.setId(lbl_Codigo.getText());
            add.setNome(txt_Nome.getText());
            add.setNomeUsuario(txt_username.getText());
            add.setEmail(txt_email.getText());
            add.setSenha(pf_Senha.getText());
            add.setBiografia(jTxt_biografia.getText());
            //
            if (rb_Masculino.isSelected()) {
                add.setGenero(rb_Masculino.getActionCommand());
            } else if (rb_Femenino.isSelected()) {
                add.setGenero(rb_Femenino.getActionCommand());
            }

            if (ch_permitido.isSelected()) {
                add.setEstado(ch_permitido.getActionCommand());
            } else if (ch_naoPermitido.isSelected()) {
                add.setEstado(ch_naoPermitido.getActionCommand());
            }

            // vai mandaa informacao para as variaves get set
            UsuarioDao Add = new UsuarioDao();
            Add.update(add);
            prencherTabela();
            limparCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    void remover() {

        try {
            Usuario add = new Usuario();
            add.setId(lbl_Codigo.getText());
            add.setNome(txt_Nome.getText());
            add.setNomeUsuario(txt_username.getText());
            add.setEmail(txt_email.getText());
            add.setSenha(pf_Senha.getText());
            add.setBiografia(jTxt_biografia.getText());
            //
            if (rb_Masculino.isSelected()) {
                add.setGenero(rb_Masculino.getActionCommand());
            } else if (rb_Femenino.isSelected()) {
                add.setGenero(rb_Femenino.getActionCommand());
            }

            if (ch_permitido.isSelected()) {
                add.setEstado(ch_permitido.getActionCommand());
            } else if (ch_naoPermitido.isSelected()) {
                add.setEstado(ch_naoPermitido.getActionCommand());
            }

            // vai mandaa informacao para as variaves get set
            UsuarioDao Add = new UsuarioDao();
            Add.delete(add);
            prencherTabela();
            limparCampos();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_pesquisar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Usuario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_Nome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pf_SenhaConfimar = new javax.swing.JPasswordField();
        pf_Senha = new javax.swing.JPasswordField();
        rb_Masculino = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rb_Femenino = new javax.swing.JRadioButton();
        lbl_Codigo = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ch_naoPermitido = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        ch_permitido = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxt_biografia = new javax.swing.JTextArea();
        btnLimpar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setTitle("Tela Usuario");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        txt_pesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyReleased(evt);
            }
        });
        jPanel1.add(txt_pesquisar);
        txt_pesquisar.setBounds(10, 270, 200, 30);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(160, 260, 30, 20);

        jT_Usuario = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIdex){
                return false;
            }
        };
        jT_Usuario.setBackground(new java.awt.Color(204, 204, 204));
        jT_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jT_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Género", "e-mail", "Username", "Estado", "Senha ", "biografia"
            }
        ));
        jT_Usuario.setToolTipText("Seelecione o Funcionário que pretendes eliminar ou  Atualizar os dados ");
        jT_Usuario.setFocusable(false);
        jT_Usuario.setPreferredSize(new java.awt.Dimension(897, 606));
        jT_Usuario.setSelectionBackground(new java.awt.Color(232, 242, 252));
        jT_Usuario.setSelectionForeground(new java.awt.Color(240, 240, 240));
        jT_Usuario.setShowHorizontalLines(false);
        jT_Usuario.setShowVerticalLines(false);
        jT_Usuario.getTableHeader().setReorderingAllowed(false);
        jT_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_UsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jT_UsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jT_UsuarioMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jT_Usuario);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 320, 560, 90);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 310, 580, 110);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        txt_Nome.setBackground(new java.awt.Color(204, 204, 255));
        txt_Nome.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        txt_Nome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_Nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_NomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_NomeMouseExited(evt);
            }
        });
        txt_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NomeKeyTyped(evt);
            }
        });
        jPanel3.add(txt_Nome);
        txt_Nome.setBounds(10, 40, 210, 30);

        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel3.add(jButton1);
        jButton1.setBounds(470, 40, 100, 110);

        pf_SenhaConfimar.setBackground(new java.awt.Color(204, 204, 255));
        pf_SenhaConfimar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        pf_SenhaConfimar.setText("1234");
        pf_SenhaConfimar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pf_SenhaConfimar.setEnabled(false);
        pf_SenhaConfimar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pf_SenhaConfimarKeyTyped(evt);
            }
        });
        jPanel3.add(pf_SenhaConfimar);
        pf_SenhaConfimar.setBounds(120, 160, 90, 30);

        pf_Senha.setBackground(new java.awt.Color(204, 204, 255));
        pf_Senha.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        pf_Senha.setText("1234");
        pf_Senha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pf_Senha.setEnabled(false);
        pf_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pf_SenhaKeyTyped(evt);
            }
        });
        jPanel3.add(pf_Senha);
        pf_Senha.setBounds(10, 160, 90, 30);

        rb_Masculino.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rb_Masculino);
        rb_Masculino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Masculino.setText("Masculino");
        rb_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_MasculinoActionPerformed(evt);
            }
        });
        jPanel3.add(rb_Masculino);
        rb_Masculino.setBounds(290, 180, 90, 25);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel2.setText("Género:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(280, 140, 60, 20);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setText("* biografia:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(280, 72, 70, 14);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ID");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(470, 10, 30, 30);

        rb_Femenino.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rb_Femenino);
        rb_Femenino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Femenino.setText("Feminino");
        rb_Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_FemeninoActionPerformed(evt);
            }
        });
        jPanel3.add(rb_Femenino);
        rb_Femenino.setBounds(290, 205, 90, 20);

        lbl_Codigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Codigo.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel3.add(lbl_Codigo);
        lbl_Codigo.setBounds(510, 10, 60, 25);

        txt_email.setBackground(new java.awt.Color(204, 204, 255));
        txt_email.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        txt_email.setToolTipText("O email  deve conter @ dominio.com");
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        jPanel3.add(txt_email);
        txt_email.setBounds(10, 100, 250, 30);

        txt_username.setBackground(new java.awt.Color(204, 204, 255));
        txt_username.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usernameKeyTyped(evt);
            }
        });
        jPanel3.add(txt_username);
        txt_username.setBounds(280, 40, 150, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setText("* Senha:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 140, 79, 20);

        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel3.add(jLabel15);
        jLabel15.setBounds(280, 170, 110, 65);

        ch_naoPermitido.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(ch_naoPermitido);
        ch_naoPermitido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ch_naoPermitido.setText("Inativo");
        ch_naoPermitido.setEnabled(false);
        ch_naoPermitido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_naoPermitidoActionPerformed(evt);
            }
        });
        jPanel3.add(ch_naoPermitido);
        ch_naoPermitido.setBounds(440, 205, 70, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel3.setText("* Estado");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(420, 140, 50, 20);

        ch_permitido.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(ch_permitido);
        ch_permitido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ch_permitido.setText("Activo");
        ch_permitido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_permitidoActionPerformed(evt);
            }
        });
        jPanel3.add(ch_permitido);
        ch_permitido.setBounds(440, 180, 70, 25);

        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jPanel3.add(jLabel9);
        jLabel9.setBounds(420, 170, 110, 65);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("* e-mail:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 80, 90, 16);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("* Nome completo:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 20, 130, 16);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("* Username:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(280, 20, 130, 16);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel11.setText("* Confirmar senha:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(120, 140, 102, 16);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTxt_biografia.setColumns(20);
        jTxt_biografia.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jTxt_biografia.setRows(5);
        jTxt_biografia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_biografiaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jTxt_biografia);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(286, 90, 170, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 580, 240);

        btnLimpar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Preencha os campos ");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar);
        btnLimpar.setBounds(230, 260, 90, 25);

        btn_eliminar.setBackground(new java.awt.Color(204, 255, 255));
        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        btn_eliminar.setText("remover ");
        btn_eliminar.setToolTipText("Seleccione um funcionaria na tabela");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar);
        btn_eliminar.setBounds(350, 260, 90, 25);

        btn_atualizar.setBackground(new java.awt.Color(204, 255, 255));
        btn_atualizar.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        btn_atualizar.setText("Atualizar");
        btn_atualizar.setToolTipText("Seleccione um funcionaria na tabela");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_atualizar);
        btn_atualizar.setBounds(470, 260, 90, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ch_permitidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_permitidoActionPerformed
        validar();
    }//GEN-LAST:event_ch_permitidoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txt_NomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NomeKeyTyped
        validar();
        setarCodigo();
    }//GEN-LAST:event_txt_NomeKeyTyped

    private void txt_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyTyped
        validar();
    }//GEN-LAST:event_txt_usernameKeyTyped

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        validar();
    }//GEN-LAST:event_txt_emailKeyTyped

    private void rb_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_MasculinoActionPerformed
        validar();
    }//GEN-LAST:event_rb_MasculinoActionPerformed

    private void rb_FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_FemeninoActionPerformed
        validar();
    }//GEN-LAST:event_rb_FemeninoActionPerformed

    private void ch_naoPermitidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_naoPermitidoActionPerformed
        validar();
    }//GEN-LAST:event_ch_naoPermitidoActionPerformed

    private void pf_SenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_SenhaKeyTyped
        vaidarEmail();
        veriaficarUsuario();
    }//GEN-LAST:event_pf_SenhaKeyTyped

    private void pf_SenhaConfimarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_SenhaConfimarKeyTyped
        vaidarEmail();
        veriaficarUsuario();
    }//GEN-LAST:event_pf_SenhaConfimarKeyTyped

    private void jT_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_UsuarioMouseClicked
        setCampos();

        btn_atualizar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        ch_naoPermitido.setEnabled(true);
    }//GEN-LAST:event_jT_UsuarioMouseClicked

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        atualizar();
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        remover();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyReleased
        Find();
    }//GEN-LAST:event_txt_pesquisarKeyReleased

    private void jTxt_biografiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_biografiaKeyTyped
        veriaficarUsuario();
    }//GEN-LAST:event_jTxt_biografiaKeyTyped

    private void txt_NomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NomeMouseEntered
        jTxt_biografia.setVisible(true);
    }//GEN-LAST:event_txt_NomeMouseEntered

    private void txt_NomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NomeMouseExited
        jTxt_biografia.setVisible(false);
    }//GEN-LAST:event_txt_NomeMouseExited

    private void jT_UsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_UsuarioMouseEntered


    }//GEN-LAST:event_jT_UsuarioMouseEntered

    private void jT_UsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_UsuarioMouseExited
        jTxt_biografia.setVisible(true);
    }//GEN-LAST:event_jT_UsuarioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox ch_naoPermitido;
    private javax.swing.JCheckBox ch_permitido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jT_Usuario;
    private javax.swing.JTextArea jTxt_biografia;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JPasswordField pf_Senha;
    private javax.swing.JPasswordField pf_SenhaConfimar;
    private javax.swing.JRadioButton rb_Femenino;
    private javax.swing.JRadioButton rb_Masculino;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
